-- ALTER TABLE `cap_cod`.`Riders` RENAME COLUMN `id` TO `RidersId`;
-- CREATE TABLE `cap_cod`.`Rides`(
-- 	`RideId` INT AUTO_INCREMENT PRIMARY KEY,
--     `DriversId` INT NOT NULL,
--     `RidersId` INT NOT NULL,
--     `Fare` DECIMAL(10, 2) NOT NULL,
--     `Rating` DECIMAL(2, 2) NOT NULL,
--     `DistanceKM`DECIMAL(5, 2) NOT NULL,
--     FOREIGN KEY (`DriversId`) REFERENCES `cap_cod`.`Drivers`(`DriversId`),
-- 	FOREIGN KEY (`RidersId`) REFERENCES `cap_cod`.`Riders`(`RidersId`)
-- );
-- ALTER TABLE `cap_cod`.`rides` ADD COLUMN `RidesId` INT;
-- CREATE TABLE `cap_cod`.`Payments`(
-- 	`paymentID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
--     `Amount` DECIMAL(10, 2) NOT NULL,
--     `paymentMethod` ENUM('Credit Card','cash','Bank Transfer','Payment Via Crypto') NOT NULL,
-- 	FOREIGN KEY (RideId) REFERENCES `cap_cod`.`Rides`(RideId) 
-- );
-- INSERT INTO drivers (driversID, Name, Rating, TotalRides) VALUES
-- (1, 'John Doe', 4.5, 120),
-- (2, 'Jane Smith', 4.2, 90),
-- (3, 'James Bond', 4.7, 150),
-- (4, 'Samantha James', 4.3, 80),
-- (5, 'Michael Brown', 4.0, 60),
-- (6, 'Nina Williams', 4.6, 200),
-- (7, 'Chris Johnson', 4.1, 110),
-- (8, 'Sarah Davis', 4.8, 100),
-- (9, 'David Lee', 3.9, 70),
-- (10, 'Emma Green', 4.4, 130),
-- (11, 'Olumide Adebayo', 4.7, 150),
-- (12, 'Grace Okafor', 4.3, 140),
-- (13, 'Julius Adedeji', 4.6, 175),
-- (14, 'Tolu Olowolagba', 4.2, 105),
-- (15, 'Fola Akinwunmi', 4.5, 125),
-- (16, 'Oluwaseun Bello', 4.1, 115),
-- (17, 'Kayode Ogunleye', 4.8, 180),
-- (18, 'Chinonso Ifeanyi', 3.8, 85),
-- (19, 'Oluwafunmilayo Bello', 4.3, 140),
-- (20, 'Adeola Akin', 4.6, 160);


-- use cap_cod;
-- select Name,Rating from drivers
-- order by rating
-- limit 5